apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-sealed-secrets
  namespace: app
spec:
  encryptedData:
    database-url: AgBy3i4OJ...encrypted...
    api-key: AgCtr8V2D...encrypted...
  template:
    metadata:
      name: app-sealed-secrets
      namespace: app
    type: Opaque
